#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}


LATEST_URL=https://github.com/mattermost/mattermost-server/releases/latest
LATEST_VER=$(curl -Ls -o /dev/null -w %{url_effective} $LATEST_URL)
VERSION=$(echo $LATEST_VER | sed 's|^.*/tag/v||')

URL=https://releases.mattermost.com/${VERSION}/mattermost-team-${VERSION}-linux-amd64.tar.gz

dl $URL /usr/local/src
