#!/bin/bash -ex

USER=mattermost
ADMIN_USER=admin
ADMIN_PASS=TurnkeyLinux1!
ADMIN_EMAIL=admin@example.com
DB_NAME=mattermost
DB_PASS=$(mcookie)
SRC=/usr/local/src/mattermost-team-*-linux-amd64.tar.gz

INSTALL_DIR=/opt/mattermost
CONF=$INSTALL_DIR/config/config.json

# start services required for mattermost
service postgresql start
service postfix start

# create db
psql postgres -c "CREATE DATABASE $DB_NAME;"
psql postgres -c "CREATE USER $USER WITH PASSWORD '$DB_PASS';"
psql postgres -c "ALTER DATABASE $DB_NAME OWNER TO $USER;"
psql postgres -c "GRANT USAGE, CREATE ON SCHEMA PUBLIC TO $USER;"

tar -zxf $SRC -C $(dirname $INSTALL_DIR)
rm -f $SRC
mkdir -p $INSTALL_DIR/data
useradd -r $USER -U
chown -R $USER:$USER $INSTALL_DIR
chmod -R g+w $INSTALL_DIR

# enable services
systemctl enable mattermost

# config mattermost
MM_SERVER="postgres://${USER}:${DB_PASS}@127.0.0.1:5432/mattermost?sslmode=disable"
sed -i "/DriverName/ s|mysql|postgres|" $CONF
sed -i "/DataSource/ s|DataSource\": \".*|DataSource\": \"$MM_SERVER\",|" $CONF
sed -i '/ListenAddress/ s| ":| "127.0.0.1:|' $CONF
sed -i '/SiteName/ s|:.*|: "TurnKey Mattermost",|' $CONF
sed -i '/AboutLink/ s|:.*|: "https://www.turnkeylinux.org/mattermost",|' $CONF
sed -i '/HelpLink/ s|:.*|: "https://www.turnkeylinux.org/forum",|' $CONF
sed -i 's|"SMTPServer": "",|"SMTPServer": "localhost",|' $CONF
sed -i 's|"SMTPPort": "",|"SMTPPort": "25",|' $CONF
sed -i 's|"SendEmailNotifications": false|"SendEmailNotifications": true|' $CONF
sed -i 's|"EnableLocalMode": false|"EnableLocalMode": true|' $CONF

cd "$INSTALL_DIR/"

su mattermost -c "bin/mattermost db migrate"
su - mattermost -s /bin/bash -c 'bin/mattermost& echo $! >/tmp/mattermost_pid'
mattermost_pid=$(cat /tmp/mattermost_pid)
rm /tmp/mattermost_pid

cd /

for i in {0..10}; do
    if [[ -S /var/tmp/mattermost_local.socket ]]; then
        break
    fi
    sleep 5
done
chown mattermost:mattermost /var/tmp/mattermost_local.socket

cd $INSTALL_DIR/bin
#su -c "./mmctl auth set local-server --config $CONF" $USER
su -c "./mmctl user create --email \"$ADMIN_EMAIL\" --password \"$ADMIN_PASS\" --username \"$ADMIN_USER\" --config-path $CONF --local --system-admin true" $USER

# add conf and log symlinks (convenience)
ln -s $INSTALL_DIR/config /etc/mattermost
ln -s $INSTALL_DIR/logs /var/log/mattermost

#confs for nginx
rm /etc/nginx/sites-enabled/tkl-default
ln -s /etc/nginx/sites-available/mattermost /etc/nginx/sites-enabled/mattermost

# Stop services
kill $mattermost_pid
while ps aux | grep -q $mattermost_pid | grep -q -v 'grep'; do
    sleep 5
done

rm -f /var/tmp/mattermost_local.socket
service postgresql stop
service postfix stop
