#!/bin/sh -ex

USER=mattermost
ADMIN_USER=admin
ADMIN_PASS=turnkey
ADMIN_EMAIL=admin@example.com
DB_NAME=mattermost
DB_PASS=$(mcookie)
SRC=/usr/local/src/mattermost-team-*-linux-amd64.tar.gz

INSTALL_DIR=/opt/mattermost
CONF=$INSTALL_DIR/config/config.json

# start services required for mattermost
service postgresql start
service postfix start

# create db
psql postgres -c "CREATE DATABASE $DB_NAME;"
psql postgres -c "CREATE USER $USER WITH PASSWORD '$DB_PASS';"
psql postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME to $USER;"

tar -zxf $SRC -C $(dirname $INSTALL_DIR)
rm -f $SRC
mkdir -p $INSTALL_DIR/data
useradd -r $USER -U
chown -R $USER:$USER $INSTALL_DIR
chmod -R g+w $INSTALL_DIR

# enable services
update-rc.d php-fastcgi defaults
update-rc.d mattermost defaults

# config mattermost
MM_SERVER="postgres://${USER}:${DB_PASS}@127.0.0.1:5432/mattermost?sslmode=disable\&connect_timeout=10"
sed -i "/DriverName/ s|mysql|postgres|" $CONF
sed -i "/DataSource/ s|mmuser.*|$MM_SERVER\",|" $CONF
sed -i '/ListenAddress/ s| ":| "127.0.0.1:|' $CONF
sed -i '/SiteName/ s|:.*|: "TurnKey Mattermost",|' $CONF
sed -i '/AboutLink/ s|:.*|: "https://www.turnkeylinux.org/mattermost",|' $CONF
sed -i '/HelpLink/ s|:.*|: "https://www.turnkeylinux.org/forum",|' $CONF
sed -i 's|"SMTPServer": "",|"SMTPServer": "localhost",|' $CONF
sed -i 's|"SMTPPort": "",|"SMTPPort": "25",|' $CONF
sed -i 's|"SendEmailNotifications": false|"SendEmailNotifications": true|' $CONF

cd $INSTALL_DIR/bin
su -c "./mattermost user create --email=\"$ADMIN_EMAIL\" --password=\"$ADMIN_PASS\" --username=\"$ADMIN_USER\" --system_admin" $USER
#su -c "./platform roles system_admin" $USER 

# add conf and log symlinks (convenience)
ln -s $INSTALL_DIR/config /etc/mattermost
ln -s $INSTALL_DIR/logs /var/log/mattermost

#confs for nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/mattermost /etc/nginx/sites-enabled/mattermost

# Stop services
service postgresql stop
service postfix stop
