#!/bin/bash -e
# regenerate pgsql password for mattermost user

. /etc/default/inithooks

CONF="/opt/mattermost/config/config.json"

PASSWORD=$(mcookie)

sed -i "s|dbpass.*|dbpass = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/pgsqlconf.py --user="mattermost" --pass="$PASSWORD"

echo $PASSWORD > "/root/mattermost-secrets.txt"
