#!/bin/bash -e
# regenerate mattermost secrets

. /etc/default/inithooks

gen-salt() {
    date +%s | sha256sum | base64 | head -c 32 ; echo
}

CONF=/opt/mattermost/config/config.json
SETTINGS="AtRestEncryptKey PublicLinkSalt InviteSalt PasswordResetSalt"

for SETTING in $SETTINGS; do
    SALT="\"$(gen-salt)\","
    sed -i "/$SETTING/ s|\":.*|\": $SALT|" $CONF
done

service mattermost restart

